Fixed .ss-blc icon
andrewgioia/keyrune pull request #235
Opened 2024-07-20 16:54 UTC by HeliumOctahelide

See this link: https://github.com/andrewgioia/keyrune/issues/234

2024-07-31 12:29 UTC, nikkitousen approved these changes

2024-08-05 22:37 UTC, Horsty80 approved these changes

2024-08-10 13:19 UTC, Horsty80 requested changes
**issue (blocking):**
I think is not ce `css/keyrune.css` file that need to be update.
You need to update `sass/_variables.sass` and after run command `npm run sass && npm run sassmin` to compile into `css` files
This actual change you propose would be overwrite at the next build less/sass command

2024-08-11 00:53 UTC, HeliumOctahelide commented
> **issue (blocking):** I think is not ce `css/keyrune.css` file that need to be update. You need to update `sass/_variables.sass` and after run command `npm run sass && npm run sassmin` to compile into `css` files This actual change you propose would be overwrite at the next build less/sass command

Ah, I see. I was not familiar with sass-related technologies before, thank you for pointing it out! I will resubmit a pull request.

2024-08-11 00:53 UTC, closed without merging